version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin2137}
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: password
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./pgadmin:/var/lib/pgadmin
       - ./sqlfiles:/home/sqlfiles
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
  schemaspy:
    container_name: schemaspy_container
    image: schemaspy/schemaspy
    command: -configFile /config/schemaspy.properties -noimplied -nopages -l
    volumes:
      - ./schemaspy-output:/output
      - ./schemaspy-config:/config
    depends_on:
      - postgres
    networks:
      - postgres
networks:
  postgres:
    driver: bridge