version: '3.5'

services:
  create_database:
    image: tabprojektcbbss/create_database:1.0.1
    build:
      context: ./backend
      dockerfile: ./docker/create-database/Dockerfile
    environment:
      PSQL_HOST: postgres
      PSQL_PORT: 5432
      PSQL_DB: postgres
      PSQL_USER: admin
      PSQL_PASSWORD: admin2137
    depends_on:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin2137}
      PGUSER: admin
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: password
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "30050:5432"
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_X_FRAME_OPTIONS: "''"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./sqlfiles:/home/sqlfiles
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    depends_on:
      - postgres
  schemaspy:
    container_name: schemaspy_container
    image: schemaspy/schemaspy
    command: -configFile /config/schemaspy.properties -noimplied -nopages -l
    volumes:
      - ./schemaspy-output:/output
      - ./schemaspy-config:/config
    depends_on:
      - postgres
  backend:
    image: tabprojektcbbss/backend:1.1.0
    build:
      context: ./backend
      dockerfile: ./docker/server/Dockerfile
    restart: unless-stopped
    environment:
      PORT: 5000
      PSQL_HOST: postgres
      PSQL_PORT: 5432
      PSQL_DB: postgres
      PSQL_USER: admin
      PSQL_PASSWORD: admin2137
      #https://pkg.go.dev/github.com/hashicorp/go-hclog@v1.2.0#Level
      LOG_LEVEL: 2
      AUTH_HOST: auth
      AUTH_PORT: 6000
    depends_on:
      - postgres
    ports:
      - "5000:5000"
  auth:
    image: tabprojektcbbss/auth:1.0.3
    build:
      context: ./backend
      dockerfile: ./docker/auth/Dockerfile
    restart: unless-stopped
    environment:
      LOG_LEVEL: 2
      PORT: 6000
      PSQL_HOST: postgres
      PSQL_PORT: 5432
      PSQL_DB: postgres
      PSQL_USER: admin
      PSQL_PASSWORD: admin2137
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_ADMIN_PASS: admin2137
    ports:
      - "6000:6000"
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local