apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o .\kube-yaml\
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o .\kube-yaml\
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: DB_ADMIN_PASS
              value: admin2137
            - name: LOG_LEVEL
              value: "2"
            - name: PORT
              value: "6000"
            - name: PSQL_DB
              value: postgres
            - name: PSQL_HOST
              value: postgres
            - name: PSQL_PASSWORD
              value: admin2137
            - name: PSQL_PORT
              value: "5432"
            - name: PSQL_USER
              value: admin
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: tabprojektcbbss/auth:1.4.4
          name: auth
          ports:
            - containerPort: 6000
          resources: { }
      restartPolicy: Always
status: { }
