apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o .\kube-yaml\
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: schemaspy
  name: schemaspy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: schemaspy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o .\kube-yaml\
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: schemaspy
    spec:
      containers:
        - args:
            - -configFile
            - /config/schemaspy.properties
            - -noimplied
            - -nopages
            - -l
          image: schemaspy/schemaspy
          name: schemaspy-container
          resources: {}
          volumeMounts:
            - mountPath: /output
              name: schemaspy-claim0
            - mountPath: /config
              name: schemaspy-claim1
      restartPolicy: Always
      volumes:
        - name: schemaspy-claim0
          persistentVolumeClaim:
            claimName: schemaspy-claim0
        - name: schemaspy-claim1
          persistentVolumeClaim:
            claimName: schemaspy-claim1
status: {}
