apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: auth
  name: auth
spec:
  ports:
    - name: auth
      port: 6000
      targetPort: 6000
  selector:
    io.kompose.service: auth
status:
  loadBalancer: { }
