apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy:
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: DB_ADMIN_PASS
              value: admin2137
            - name: LOG_LEVEL
              value: "2"
            - name: PORT
              value: "6000"
            - name: PSQL_DB
              value: postgres
            - name: PSQL_HOST
              value: postgres-postgresql
            - name: PSQL_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: PSQL_PORT
              value: "5432"
            - name: PSQL_USER
              value: postgres
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: tabprojektcbbss/auth:1.5.0
          name: auth
          ports:
            - containerPort: 6000
          resources: { }
      restartPolicy: Always
status: { }
