apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: api
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: backend
status:
  loadBalancer: { }
